apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.name }}-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
#      imagePullSecrets:
#        - name: {{ .Values.imagePullSecret}}
      containers:
        - name: {{ .Values.name }}
          image: '{{ .Values.image.name }}:{{ .Values.image.tag }}'
#          ports:
#            - containerPort: {{ .Values.port}}
#          envFrom:
#            - configMapRef:
#                name: "{{ .Values.name }}-configmap"
