apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.name }}-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: '{{ .Values.image.name }}:{{ .Values.image.tag }}'
          volumeMounts:
          - name: lint-workflow
            mountPath: {{ .Values.config.localWorkflowPath }}
          envFrom:
            - configMapRef:
                name: "{{ .Values.name }}-configmap"
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.config.port }}
            initialDelaySeconds: 3
            periodSeconds: 5
      volumes:
      - name: lint-workflow
        configMap:
          name: lint-workflow
