name: reposipoint-backend
port: 80
# imagePullSecret: 
image: 
  name: nginx
  tag: latest
config:
  workflowFileName: lint.yaml
  localWorkflowPath: /workflows
  remoteWorkflowPath: .github/workflows
  githubPersonalAccessToken: 
  githubApiUrl: https://api.github.com
  githubOwner: oavner
  host: 0.0.0.0
  port: 80


